# Generated by Django 5.2.4 on 2025-08-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_teacher_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_staff',
        ),
    ]
